
CREATE TABLE IF NOT EXISTS "_cliente" (
	"id" SERIAL NOT NULL,
	"nome" VARCHAR(200) NOT NULL,
	"telefone" VARCHAR(15) NOT NULL,
	"email" VARCHAR(200) NOT NULL,
	"endereco" VARCHAR(500) NULL DEFAULT NULL,
	"x" INTEGER NULL DEFAULT NULL,
	"y" INTEGER NULL DEFAULT NULL,
	PRIMARY KEY ("id")
);
